### ISSUE TITLE
Can't install wordpress template

### ISSUE THREAD

**Issue by Kittybiccy** [timcreative/coming-sssoon-wordpress-plugin#1]
Hi there, 
I'm trying to install the theme but am unable as the 'style.css' file is missing. I can see it's in the 'lib/css' folder but does it need to be in a different directory? How can I install the template?
Thanks!
Hannah

**Comment by alexandru-paduraru** [comment]
Hi @Kittybiccy and thank you for your interest in our products. Please download the Wordpress Plugin Package which can be found [here](http://www.creative-tim.com/product/coming-sssoon-page-wordpress-plugin) not the plain HTML/CSS package.

Best,
Alex

**Comment by Kittybiccy** [comment]
Hi Alex, I have downloaded this already however when I try and install it Wordpress says it cannot be installed as that .css file is missing. Do you know how I can install it?
Thanks
